#!/bin/sh /etc/rc.common

START=90
SERVICE_PID_FILE=/var/run/sigma-dut.pid
SERVICE_DAEMONIZE=1
SERVICE_WRITE_PID=1

start () {
	config_load sigma-dut
	local ARGS

	local enable
	config_get_bool enable global enable 0
	[ "${enable}" -gt 0 ] || return

	local port radio_name debug
	local main_intf

	config_get port global port
	[ -n "${port}" ] && append ARGS "-p ${port} "

	config_get radio_name global radio_name
	[ -n "${radio_name}" ] && append ARGS "-R ${radio_name} "

	config_get main_intf global main_intf
	[ -n "${main_intf}" ] && append ARGS "-M ${main_intf} "

	config_get bridge_iface global bridge_iface
	[ -n "${bridge_iface}" ] && append ARGS "-b ${bridge_iface} "

	config_get vendor global vendor
	[ -n "${vendor}" ] && append ARGS "-N ${vendor} "

	config_get model global model
	[ -n "${model}" ] && append ARGS "-o ${model} "

	config_get version global version
	[ -n "${version}" ] && append ARGS "-O ${version} "

	config_get debug global debug
	if [ "${debug}" == on ]; then
		[ -n "${debug}" ] && append ARGS "-Y -d "
	fi

	service_start /usr/sbin/sigma_dut -c MAC80211 -H /tmp/hostapd_log.txt ${ARGS}
}

stop() {
	service_stop /usr/sbin/sigma_dut
}
