#!/bin/sh /etc/rc.common
START=90
SERVICE_PID_FILE=/var/run/sigma-dut.pid
SERVICE_DAEMONIZE=1
SERVICE_WRITE_PID=1

start () {
	config_load sigma-dut
	local ARGS
	local enable ifname radio_name

	config_get_bool enable global enable 0
	[ "${enable}" -gt 0 ] || return

	config_get port global port
	[ -n "${port}" ] && append ARGS "-p ${port} "

	config_get ifname global ifname
	[ -n "${ifname}" ] && append ARGS "-M ${ifname} "

	config_get radio_name global radio_name
	[ -n "${radio_name}" ] && append ARGS "-R ${radio_name} "

	service_start /usr/sbin/sigma_dut -c MAC80211 ${ARGS}
}

stop() {
	service_stop /usr/sbin/sigma_dut
}
